---
title: "Making Data Frames for 2 Days"
format: html
---

A004-SD012-04-07
```{r}
library(purrr)
library(soundecology)
library(tidyverse)
library(here)
library(stringr)
library(hms)
```

```{r}
A4_7_paths <- list.files(here("A004_SD012_04_07"), pattern = "\\.WAV$",
                    full.names = TRUE)

wav_files_47 <- map(A4_7_paths, readWave)
AEI_allWAV_47<-map(wav_files_47, acoustic_evenness)
BEI_allWAV_47<-map(wav_files_47, bioacoustic_index)
ADI_allWAV_47<-map(wav_files_47, acoustic_diversity)
ACI_allWAV_47<-map(wav_files_47, acoustic_complexity)
ndsi_allWAV_47<-map(wav_files_47, soundecology::ndsi)
```

Single value indices - Biophony, BEI, and AEI

```{r}
AEI_4_7<-as.data.frame(AEI_allWAV_47)|>
  select(starts_with("aei_left"))|>
  pivot_longer(everything(), names_to = "aei_name", values_to = "AEI")

BEI_4_7<-as.data.frame(BEI_allWAV_47)|>
  select(starts_with("left_area"))|>
  pivot_longer(everything(), names_to = "bei_name", values_to = "BEI")

Bio_4_7<-as.data.frame(ndsi_allWAV_47)|>
  select(starts_with("biophony_left"))|>
  pivot_longer(everything(), names_to = "biophony_name", values_to = "Biophony")

paths_date <-str_remove(A4_7_paths, paste0(here(), "/A004_SD012_04_07"))

single_indices<-as_tibble(cbind(paths_date, AEI_4_7$AEI, BEI_4_7$BEI, Bio_4_7$Biophony))

```

Multiple Indices - ACI and ADI 

For loop making lists of left values
```{r}
ACI_all_47<-vector("list", length(c(1:350)))
ADI_all_47<-vector("list", length(c(1:350)))
n<-350
for (i in 1:n){
    ACI_all_47[i]<-(as.data.frame(ACI_allWAV_47[[i]]$aci_fl_left_vals))
    ADI_all_47[i]<-(as.data.frame(ADI_allWAV_47[[i]]$left_band_values))
} 

```

```{r}
multiple_indices<-as.tibble(cbind(ADI_all_47, ACI_all_47))

df_names<- c("Paths_date", "AEI", "BEI", "Biophony", "ADI","ACI")

Full_4_7_df<-bind_cols(single_indices,multiple_indices)
names(Full_4_7_df)<-df_names

New_df_4_7<-Full_4_7_df|>
  mutate(Biophony = as.numeric(Biophony),
         AEI = as.numeric(AEI),
         BEI = as.numeric(BEI))|>
  separate(Paths_date, into = c("Date", "Time"), sep = "_")|>
  separate(Time, into = c("time", "temp"), sep = "\\.")|>
  separate(time, into = c("hours","other"), sep = 2)|>
  separate(other, into = c("min", "sec"), sep = 2)|>
  mutate(Date = parse_number(Date))|>
  unite("time", c("Date","hours", "min","sec"), sep = ":")|>
  mutate(time = ymd_hms(time))|>
  select(-temp)

save(New_df_4_7, file = "A004_SD012_04_07.rda")
load("A004_SD012_04_07.rda")
```

A004_SD012_04_08

```{r}
A4_8_paths <- list.files(here("A004_SD012_04_08"), pattern = "\\.WAV$",
                    full.names = TRUE)

wav_files_48 <- map(A4_8_paths, readWave)
AEI_allWAV_48<-map(wav_files_48, acoustic_evenness)
BEI_allWAV_48<-map(wav_files_48, bioacoustic_index)
ADI_allWAV_48<-map(wav_files_48, acoustic_diversity)
ACI_allWAV_48<-map(wav_files_48, acoustic_complexity)
ndsi_allWAV_48<-map(wav_files_48, soundecology::ndsi)
```

Single Indices - Acoustic evenness, bioacoustic index, and biophony
```{r}
AEI_4_8<-as.data.frame(AEI_allWAV_48)|> 
  select(starts_with("aei_left"))|>
  pivot_longer(everything(), names_to = "aei_name", values_to = "AEI")

BEI_4_8<-as.data.frame(BEI_allWAV_48)|>
  select(starts_with("left_area"))|>
  pivot_longer(everything(), names_to= "bei_name", values_to = "BEI")

Biophony_4_8<-as.data.frame(ndsi_allWAV_48)|>
  select(starts_with("biophony_left"))|>
  pivot_longer(everything(), names_to = "bio_name", values_to = "Biophony")

paths_date <-str_remove(A4_8_paths, paste0(here(), "/A004_SD012_04_08"))
single_indices_48<-cbind(paths_date,AEI_4_8$AEI, BEI_4_8$BEI, Biophony_4_8$Biophony )

```

Multiple Indices
```{r}
ACI_all_48<-vector("list", length(c(1:350)))
ADI_all_48<-vector("list", length(c(1:350)))
n<-350
for (i in 1:n){
    ACI_all_48[i]<-(as.data.frame(ACI_allWAV_48[[i]]$aci_fl_left_vals))
    ADI_all_48[i]<-(as.data.frame(ADI_allWAV_48[[i]]$left_band_values))
} 

multiple_indices_48<-as.tibble(cbind(ADI_all_48, ACI_all_48))
```

Compiling all into one data frame 

```{r}
Full_4_8<-bind_cols(single_indices_48, multiple_indices_48)
names(Full_4_8)<-df_names

New_df_4_8<-Full_4_8|>
  mutate(Biophony = as.numeric(Biophony),
         AEI = as.numeric(AEI),
         BEI = as.numeric(BEI))|>
  separate(Paths_date, into = c("Date", "Time"), sep = "_")|>
  separate(Time, into = c("time", "temp"), sep = "\\.")|>
  separate(time, into = c("hours","other"), sep = 2)|>
  separate(other, into = c("min", "sec"), sep = 2)|>
  mutate(Date = parse_number(Date))|>
  unite("time", c("Date","hours", "min","sec"), sep = ":")|>
  mutate(time = ymd_hms(time))|>
  select(-temp)

save(New_df_4_8, file = "A004_SD012_04_08.rda")
load("A004_SD012_04_08.rda")
```

```{r}
both_days <- bind_rows(New_df_4_7, New_df_4_8) |>
  mutate(day = as.factor(lubridate::day(time)),
         only_time = hms::as_hms(time))
```

Biophony visual for the two days 
```{r}
ggplot(data = both_days, aes(x = only_time, y = Biophony, color = day))+
  geom_line()+
  scale_color_viridis_d()+
  theme_minimal()

```

Acoustic Evenness Index visual for the two days 
```{r}
ggplot(data = both_days, aes(x = only_time, y = AEI, color = day))+
  geom_line()+
  scale_color_viridis_d()+
  theme_minimal()
```

Bioacoustic Index visual for the two days
```{r}
ggplot(data = both_days, aes(x = only_time, y = BEI, color = day))+
  geom_line()+
    scale_color_viridis_d()+
  theme_minimal()
```


